layout: [
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.25, 1,],
  [1.25, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],
  [1.5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.75,],
  [1.75, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,],
  [1.25, 1, 1, 1, 1, 2.5, 1, 1, 1, 1, 1, 1],
]
plate_height: 16
plate_split: [7, 7, 7, 7, 7,]
excess_port_width: 200
frame_wall_width: 25
frame_height: 150
bot_panel_height: 20
base_key_size: 181
key_gap: 9